// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: global_settings.sql

package db

import (
	"context"
)

const checkGlobalSettingsExists = `-- name: CheckGlobalSettingsExists :one
SELECT EXISTS (
  SELECT 1
  FROM global_settings
)
`

func (q *Queries) CheckGlobalSettingsExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, checkGlobalSettingsExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createGlobalSettings = `-- name: CreateGlobalSettings :one
INSERT INTO "global_settings" ("disable_comments", "disable_likes", "disable_dislikes", "disable_views", "disable_ads")
VALUES (false, false, true, false, false)
RETURNING global_settings_id, disable_comments, disable_likes, disable_dislikes, disable_views, disable_ads
`

func (q *Queries) CreateGlobalSettings(ctx context.Context) (GlobalSetting, error) {
	row := q.db.QueryRow(ctx, createGlobalSettings)
	var i GlobalSetting
	err := row.Scan(
		&i.GlobalSettingsID,
		&i.DisableComments,
		&i.DisableLikes,
		&i.DisableDislikes,
		&i.DisableViews,
		&i.DisableAds,
	)
	return i, err
}

const getGlobalSettings = `-- name: GetGlobalSettings :many
SELECT global_settings_id, disable_comments, disable_likes, disable_dislikes, disable_views, disable_ads FROM "global_settings"
`

func (q *Queries) GetGlobalSettings(ctx context.Context) ([]GlobalSetting, error) {
	rows, err := q.db.Query(ctx, getGlobalSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalSetting
	for rows.Next() {
		var i GlobalSetting
		if err := rows.Scan(
			&i.GlobalSettingsID,
			&i.DisableComments,
			&i.DisableLikes,
			&i.DisableDislikes,
			&i.DisableViews,
			&i.DisableAds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetGlobalSettings = `-- name: ResetGlobalSettings :exec
UPDATE "global_settings"
SET
    "disable_comments" = false,
    "disable_likes" = false,
    "disable_dislikes" = true,
    "disable_views" = false,
    "disable_ads" = false
WHERE "global_settings_id" = (SELECT "global_settings_id" FROM "global_settings" LIMIT 1)
`

func (q *Queries) ResetGlobalSettings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetGlobalSettings)
	return err
}

const updateGlobalSettings = `-- name: UpdateGlobalSettings :exec
UPDATE "global_settings"
SET
    "disable_comments" = $1,
    "disable_likes" = $2,
    "disable_dislikes" = $3,
    "disable_views" = $4,
    "disable_ads" = $5
WHERE "global_settings_id" = (SELECT "global_settings_id" FROM "global_settings" LIMIT 1)
`

type UpdateGlobalSettingsParams struct {
	DisableComments bool
	DisableLikes    bool
	DisableDislikes bool
	DisableViews    bool
	DisableAds      bool
}

func (q *Queries) UpdateGlobalSettings(ctx context.Context, arg UpdateGlobalSettingsParams) error {
	_, err := q.db.Exec(ctx, updateGlobalSettings,
		arg.DisableComments,
		arg.DisableLikes,
		arg.DisableDislikes,
		arg.DisableViews,
		arg.DisableAds,
	)
	return err
}
