// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ad struct {
	ID          pgtype.UUID
	Title       pgtype.Text
	Description pgtype.Text
	ImageUrl    pgtype.Text
	TargetUrl   pgtype.Text
	Placement   pgtype.Text
	Status      pgtype.Text
	Clicks      pgtype.Int4
	StartDate   pgtype.Timestamptz
	EndDate     pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type AnalyticsDaily struct {
	AnalyticsDate  pgtype.Date
	TotalViews     int32
	TotalLikes     int32
	TotalDislikes  int32
	TotalComments  int32
	TotalAdsClicks int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Category struct {
	CategoryID   pgtype.UUID
	CategoryName string
	Slug         string
}

type Comment struct {
	CommentID       pgtype.UUID
	ContentID       pgtype.UUID
	UserID          pgtype.UUID
	CommentText     string
	Score           int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	IsDeleted       pgtype.Bool
	ParentCommentID pgtype.UUID
}

type CommentReaction struct {
	CommentID pgtype.UUID
	UserID    pgtype.UUID
	Reaction  string
}

type Content struct {
	ContentID           pgtype.UUID
	UserID              pgtype.UUID
	CategoryID          pgtype.UUID
	Title               string
	Slug                string
	Thumbnail           pgtype.Text
	ContentDescription  string
	CommentsEnabled     bool
	ViewCountEnabled    bool
	LikeCountEnabled    bool
	DislikeCountEnabled bool
	Status              string
	ViewCount           int32
	LikeCount           int32
	DislikeCount        int32
	CommentCount        int32
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	PublishedAt         pgtype.Timestamptz
	IsDeleted           pgtype.Bool
}

type ContentReaction struct {
	ContentID pgtype.UUID
	UserID    pgtype.UUID
	Reaction  string
}

type ContentTag struct {
	ContentID pgtype.UUID
	TagID     pgtype.UUID
}

type GlobalSetting struct {
	GlobalSettingsID pgtype.UUID
	DisableComments  bool
	DisableLikes     bool
	DisableDislikes  bool
	DisableViews     bool
	DisableAds       bool
}

type Medium struct {
	MediaID      pgtype.UUID
	ContentID    pgtype.UUID
	MediaType    string
	MediaUrl     string
	MediaCaption string
	MediaOrder   int32
}

type Session struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Username     string
	RefreshToken string
	UserAgent    string
	ClientIp     string
	IsBlocked    bool
	ExpiresAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type Tag struct {
	TagID   pgtype.UUID
	TagName string
	Slug    string
}

type User struct {
	UserID        pgtype.UUID
	Username      string
	Email         string
	Password      string
	Pfp           string
	Role          string
	EmailVerified pgtype.Bool
	Banned        pgtype.Bool
	IsDeleted     pgtype.Bool
	CreatedAt     pgtype.Timestamptz
}

type View struct {
	ViewID    pgtype.UUID
	ContentID pgtype.UUID
	UserID    pgtype.UUID
}
